### ISSUE TITLE
missing resources

### ISSUE THREAD

**Issue by gdi2290** [mgechev/angular2-performance-checklist#1]
http2 and webpack
https://medium.com/webpack/webpack-http-2-7083ec3f3ce6
webpack offline(/ServiceWorker)
https://github.com/NekR/offline-plugin
webpack webworker-loader
https://github.com/webpack/worker-loader
preboot for server-side rendering
https://github.com/angular/preboot

**Comment by mgechev** [comment]
Would you open a PR with these links? I guess this should be in the **Tools** section.

**Comment by areai51** [comment]
if its ok with you guys I could add them & send the PR I just sent a PR before I saw this will send another one with the above items added in :-)

**Comment by mgechev** [comment]
@areai51 thanks for the PR!
